swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /predict:
    post:
      operationId: predict_sale.predictSaleFunc
      tags:
        - predict
      summary: Predicts the price of sale
      description: Predict the price of sale in third month based on sale in first and second month and rate
      parameters:
        - name: prediction_data
          in: body
          description: Sale forecast data
          required: True
          schema:
            type: object
            properties:
              sale1:
                type: string
                description: Sale for first month
              sale2:
                type: string
                description: Sale for second month
              rate:
                type: string
                description: Rate
      responses:
        200:
          description: Successfully predicted sale for third month
          schema:
            properties:
              sale3:
                type: string